language: groovy

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - ./gradlew --no-daemon --version

script: ./gradlew clean build jacocoTestReport

jdk:
  - oraclejdk8

env: TERM=dumb

after_success: ./gradlew coveralls
